sftpHost = "ftp.support.wso2.com"
sftpUsername = "test-06032025"
sftpPassword = "yByRu9^=FmnOJ0(qD2^Q"

[monitoredFolders]
clearview = "/test-06032025/ccda/clinic_A"

[clinicFhirConfigs.clearview]
resolverBaseUrl = "http://localhost:8090"
resolverPath = "/resolver/orgs"

[ballerina.http.traceLogAdvancedConfig]
# Enable printing trace logs on the Console. The default value is `false`.
console = true
